### ISSUE TITLE
Compile error: alsa missing

### ISSUE THREAD

**Issue by astrale-sharp** [nixon-voxell/bevy_vello_renderer#2]
Hey :)

Very nice idea :D
I get the following error when trying to run the typst_example

I have alsa on my ubuntu system, installed via `sudo apt install alsa-{base; tools; source, etc... }`

```
  --- stderr
  thread 'main' panicked at /home/astrale/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alsa-sys-0.3.1/build.rs:13:18:
  `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "alsa"` did not exit successfully: exit status: 1
  error: could not find system library 'alsa' required by the 'alsa-sys' crate

  --- stderr
  Package alsa was not found in the pkg-config search path.
  Perhaps you should add the directory containing `alsa.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'alsa' found

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```

**Comment by nixonyh** [comment]
Hey @astrale-sharp thanks for trying it out! Is this a Bevy MotionGfx thing or a Vello Renderer thing? I have not test it on any Linux device yet, so am not familiar with this haha.

I guess I will try to test it out soon.

**Comment by astrale-sharp** [comment]
All I know is the problematic crate is `alsa-sys v0.3.1`  which I guess is a vello rendered thing

**Comment by nixonyh** [comment]
Hey I think this might be related to your issue: https://askubuntu.com/questions/1281211/no-package-alsa-found-in-ubuntu-18-04

From my search I believe alsa is some sort of Linux sound architecture. Which I think could be related to Bevy instead of Vello?

**Comment by astrale-sharp** [comment]
- Thanks it unstuck me 
- now libudev is reported missing
- sudo apt install libudev-dev solved that problem
- It compiles!
- Now i get this error when running the code:
```
[
    SourceDiagnostic {
        severity: Error,
        span: Span(
            15673696619813,
        ),
        message: "file not found (searched at .\\assets/themes/Monokai Pro.tmTheme)",
        trace: [],
        hints: [],
    },
]
```

**Comment by astrale-sharp** [comment]
I commented this line // #set raw(theme: "themes/Monokai Pro.tmTheme")
The result is *Hella cute*

you get the frames from the generated svg I assume, I think next step would be to find in metadata or `page` the information we're looking for

for instance, using polylux we could run a document in a frame per page mode and use metadata to decide the easing we want

**Comment by astrale-sharp** [comment]
Commented the line that set the theme and got it to work!
I'll just go put more thought in discussion and close this ;)
