### ISSUE TITLE
Fix attribution

### ISSUE THREAD

**Issue by nuzzles** [nixon-voxell/bevy_vello_renderer#4]
You attributed us by mentioning https://github.com/vectorgameexperts/bevy-vello in the README, thanks!

We recently moved our org and name to https://github.com/loopystudios/bevy_vello (`bevy_vello` now, instead of `bevy-vello`)

Do you mind updating your link? :)

Also, we'd welcome a change to bevy_vello that allows rendering to a scene. We've been toying with the idea that `svg` and `lottie` should be features, and the default behavior should be to render scenes, similar to what you've done here! If you want, we would happily PRs to help take the burden off maintaining this yourself!

**Comment by nixonyh** [comment]
Hey sure thing, I will change it ASAP!

> Also, we'd welcome a change to bevy_vello that allows rendering to a scene. We've been toying with the idea that svg and lottie should be features, and the default behavior should be to render scenes, similar to what you've done here! If you want, we would happily PRs to help take the burden off maintaining this yourself!

That would be awesome! However, at the moment the [bevy_motiongfx](https://github.com/nixon-voxell/bevy_motiongfx) heavily relies on this repo, if bevy_vello can provide similar (or better) integration, I am all open to it!

edit: perhaps I think I misunderstood abit, if u guys would want to contribute, feel free to do so! I would be more than happy tbh! :D

**Comment by nixonyh** [comment]
marking it as done as I have fixed the attribution.
